### ISSUE TITLE
Reference to closed Juju mailing list in maintainers metadata

### ISSUE THREAD

**Issue by Cynerva** [juju-solutions/charm-kubeflow-tf-serving#1]
From metadata.yaml:

https://github.com/juju-solutions/charm-kubeflow-tf-serving/blob/0b83f7d9c060b91f634921ac1f0f3f63f0198567/metadata.yaml#L3-L4

Wasn't the Juju mailing list closed recently?

https://lists.ubuntu.com/archives/juju/2018-July/010043.html

> Both the juju and juju-dev mailing lists will be closed for posting
shortly.

**Comment by johnsca** [comment]
Yep, copypasta.  Is there a better address to use than my own?
