### ISSUE TITLE
Changes to config or resources are ignored?

### ISSUE THREAD

**Issue by Cynerva** [juju-solutions/charm-kubeflow-tf-serving#2]
Disclaimer: This might not be relevant since I'm reviewing this from a traditional charm perspective and I don't know anything about caas.

It looks like the `start_charm` handler will only run once. So if you ever attach a new `tf-serving-image` resource, or change the `model` config option, the changes will just be silently ignored. Is that something we should be concerned about?

**Comment by johnsca** [comment]
You are correct, this should be handled.
